clc
clear

% AXIAL LOAD GENERATED BY THE HARMONIC DRIVE
% as of page 38: https://harmonicdrive.de/fileadmin/user_upload/2014_11-ED_1019657_HFUC-2A.pdf

% input data
u = symunit;
hd_name = "HFUC-8-2A";
hd_size = 8;
T_out = 2.5;            % Nm        output torque
mu = 0.07;              % -         coefficient of friction

%calculations;
T_out = T_out*u.N*u.m;
D = hd_size*0.00254*u.m;            
F_ax = 2*(T_out/D)*mu*tand(20);
F_ax = vpa(F_ax, 3)                % convert the symbolic to decimal number


