% -------------------------------------------------------------------
%  Generated by MATLAB on 23-Apr-2024 12:09:46
%  MATLAB version: 24.1.0.2568132 (R2024a) Update 1
% -------------------------------------------------------------------
                                                 

Efficiency = Simulink.Parameter;
Efficiency.Value = 0.754;
Efficiency.Complexity = 'real';
Efficiency.HasCoderInfo = false;
Efficiency.Description = '';
Efficiency.DataType = 'auto';
Efficiency.Min = [];
Efficiency.Max = [];
Efficiency.DocUnits = '';

GearRatio = Simulink.Parameter;
GearRatio.Value = 100;
GearRatio.Complexity = 'real';
GearRatio.HasCoderInfo = false;
GearRatio.Description = '';
GearRatio.DataType = 'auto';
GearRatio.Min = [];
GearRatio.Max = [];
GearRatio.DocUnits = '';

Ktau221 = Simulink.Parameter;
Ktau221.Value = 0.0322;
Ktau221.Complexity = 'real';
Ktau221.HasCoderInfo = false;
Ktau221.Description = '';
Ktau221.DataType = 'auto';
Ktau221.Min = [];
Ktau221.Max = [];
Ktau221.DocUnits = '';

Ktau321 = Simulink.Parameter;
Ktau321.Value = 0.0358;
Ktau321.Complexity = 'real';
Ktau321.HasCoderInfo = false;
Ktau321.Description = '';
Ktau321.DataType = 'auto';
Ktau321.Min = [];
Ktau321.Max = [];
Ktau321.DocUnits = 'N*m/A';

Kvisc = Simulink.Parameter;
Kvisc.Value = 5E-5;
Kvisc.Complexity = 'real';
Kvisc.HasCoderInfo = false;
Kvisc.Description = '';
Kvisc.DataType = 'auto';
Kvisc.Min = [];
Kvisc.Max = [];
Kvisc.DocUnits = 'N*m*s/rad';

Tau_noload = Simulink.Parameter;
Tau_noload.Value = 0.0059;
Tau_noload.Complexity = 'real';
Tau_noload.HasCoderInfo = false;
Tau_noload.Description = '';
Tau_noload.DataType = 'auto';
Tau_noload.Min = [];
Tau_noload.Max = [];
Tau_noload.DocUnits = 'N*m';

Tau_nom = Simulink.Parameter;
Tau_nom.Value = 2.4;
Tau_nom.Complexity = 'real';
Tau_nom.HasCoderInfo = false;
Tau_nom.Description = '';
Tau_nom.DataType = 'auto';
Tau_nom.Min = [];
Tau_nom.Max = [];
Tau_nom.DocUnits = 'N*m';

smiData = struct;
smiData.RigidTransform = struct;
smiData.RigidTransform(1).translation = ...
  [0 0 0];
smiData.RigidTransform(1).angle = 0;
smiData.RigidTransform(1).axis = [0 0 0];
smiData.RigidTransform(1).ID = 'B[1110:-:1442]';
smiData.RigidTransform(1).ID = convertCharsToStrings( ...
  smiData.RigidTransform(1).ID);
smiData.RigidTransform(2).translation = ...
  [0.59999999999999609 -7.105427357601188E-15 -3.5527136788005009E-15];
smiData.RigidTransform(2).angle = 3.1415926535897931;
smiData.RigidTransform(2).axis = [-1 0 0];
smiData.RigidTransform(2).ID = 'F[1110:-:1442]';
smiData.RigidTransform(2).ID = convertCharsToStrings( ...
  smiData.RigidTransform(2).ID);
smiData.RigidTransform(3).translation = ...
  [0 0 0];
smiData.RigidTransform(3).angle = 0;
smiData.RigidTransform(3).axis = [0 0 0];
smiData.RigidTransform(3).ID = 'B[1863:-:3310]';
smiData.RigidTransform(3).ID = convertCharsToStrings( ...
  smiData.RigidTransform(3).ID);
smiData.RigidTransform(4).translation = ...
  [0 1.7763568394002505E-15 -6.5];
smiData.RigidTransform(4).angle = 1.5707963267948966;
smiData.RigidTransform(4).axis = [7.8504622934188758E-17 7.8504622934188758E-17 ...
                                  -1];
smiData.RigidTransform(4).ID = 'F[1863:-:3310]';
smiData.RigidTransform(4).ID = convertCharsToStrings( ...
  smiData.RigidTransform(4).ID);
smiData.RigidTransform(5).translation = ...
  [0 0 0];
smiData.RigidTransform(5).angle = 0;
smiData.RigidTransform(5).axis = [0 0 0];
smiData.RigidTransform(5).ID = 'B[1865:-:3399]';
smiData.RigidTransform(5).ID = convertCharsToStrings( ...
  smiData.RigidTransform(5).ID);
smiData.RigidTransform(6).translation = ...
  [0 8.8817841970012523E-16 -4.5000000000000142];
smiData.RigidTransform(6).angle = 4.5519144009631418E-15;
smiData.RigidTransform(6).axis = [-0 -8.6651553141475635E-17 1];
smiData.RigidTransform(6).ID = 'F[1865:-:3399]';
smiData.RigidTransform(6).ID = convertCharsToStrings( ...
  smiData.RigidTransform(6).ID);
smiData.RigidTransform(7).translation = ...
  [0 0 0];
smiData.RigidTransform(7).angle = 0;
smiData.RigidTransform(7).axis = [0 0 0];
smiData.RigidTransform(7).ID = 'B[2189:-:2190]';
smiData.RigidTransform(7).ID = convertCharsToStrings( ...
  smiData.RigidTransform(7).ID);
smiData.RigidTransform(8).translation = ...
  [-5.1763809020504157 19.318516525781366 16.15];
smiData.RigidTransform(8).angle = 1.3089969389957472;
smiData.RigidTransform(8).axis = [-9.1187037460059935E-17 9.1187037460059935E-17 ...
                                  -1];
smiData.RigidTransform(8).ID = 'F[2189:-:2190]';
smiData.RigidTransform(8).ID = convertCharsToStrings( ...
  smiData.RigidTransform(8).ID);
smiData.RigidTransform(9).translation = ...
  [0 0 0];
smiData.RigidTransform(9).angle = 0;
smiData.RigidTransform(9).axis = [0 0 0];
smiData.RigidTransform(9).ID = 'B[2189:-:2966]';
smiData.RigidTransform(9).ID = convertCharsToStrings( ...
  smiData.RigidTransform(9).ID);
smiData.RigidTransform(10).translation = ...
  [-8.57011528587179 -27.180933096324473 16.149999999999995];
smiData.RigidTransform(10).angle = 1.3089969389957472;
smiData.RigidTransform(10).axis = [-9.1187037460059935E-17 9.1187037460059935E-17 ...
                                   -1];
smiData.RigidTransform(10).ID = 'F[2189:-:2966]';
smiData.RigidTransform(10).ID = convertCharsToStrings( ...
  smiData.RigidTransform(10).ID);
smiData.RigidTransform(11).translation = ...
  [0 0 0];
smiData.RigidTransform(11).angle = 0;
smiData.RigidTransform(11).axis = [0 0 0];
smiData.RigidTransform(11).ID = 'B[2189:-:2967]';
smiData.RigidTransform(11).ID = convertCharsToStrings( ...
  smiData.RigidTransform(11).ID);
smiData.RigidTransform(12).translation = ...
  [21.012404099088542 -19.254320917046321 16.149999999999995];
smiData.RigidTransform(12).angle = 1.3089969389957472;
smiData.RigidTransform(12).axis = [-9.1187037460059935E-17 9.1187037460059935E-17 ...
                                   -1];
smiData.RigidTransform(12).ID = 'F[2189:-:2967]';
smiData.RigidTransform(12).ID = convertCharsToStrings( ...
  smiData.RigidTransform(12).ID);
smiData.RigidTransform(13).translation = ...
  [0 0 0];
smiData.RigidTransform(13).angle = 0;
smiData.RigidTransform(13).axis = [0 0 0];
smiData.RigidTransform(13).ID = 'B[3310:-:3503]';
smiData.RigidTransform(13).ID = convertCharsToStrings( ...
  smiData.RigidTransform(13).ID);
smiData.RigidTransform(14).translation = ...
  [8.4376926933473612E-15 -10.249999999999998 -2.1000000000000174];
smiData.RigidTransform(14).angle = 3.1415926535897931;
smiData.RigidTransform(14).axis = [0 2.2204460492503131E-16 -1];
smiData.RigidTransform(14).ID = 'F[3310:-:3503]';
smiData.RigidTransform(14).ID = convertCharsToStrings( ...
  smiData.RigidTransform(14).ID);
smiData.RigidTransform(15).translation = ...
  [0 0 0];
smiData.RigidTransform(15).angle = 0;
smiData.RigidTransform(15).axis = [0 0 0];
smiData.RigidTransform(15).ID = 'B[3310:-:3545]';
smiData.RigidTransform(15).ID = convertCharsToStrings( ...
  smiData.RigidTransform(15).ID);
smiData.RigidTransform(16).translation = ...
  [1.0658141036401503E-14 -10.249999999999996 -2.1000000000000152];
smiData.RigidTransform(16).angle = 1.5707963267948966;
smiData.RigidTransform(16).axis = [-7.8504622934188758E-17 -7.8504622934188758E-17 ...
                                   1];
smiData.RigidTransform(16).ID = 'F[3310:-:3545]';
smiData.RigidTransform(16).ID = convertCharsToStrings( ...
  smiData.RigidTransform(16).ID);
smiData.RigidTransform(17).translation = ...
  [0 0 0];
smiData.RigidTransform(17).angle = 0;
smiData.RigidTransform(17).axis = [0 0 0];
smiData.RigidTransform(17).ID = 'B[3310:-:3546]';
smiData.RigidTransform(17).ID = convertCharsToStrings( ...
  smiData.RigidTransform(17).ID);
smiData.RigidTransform(18).translation = ...
  [8.8817864908050808E-15 -10.25 -2.1000000000000103];
smiData.RigidTransform(18).angle = 0;
smiData.RigidTransform(18).axis = [0 0 0];
smiData.RigidTransform(18).ID = 'F[3310:-:3546]';
smiData.RigidTransform(18).ID = convertCharsToStrings( ...
  smiData.RigidTransform(18).ID);
smiData.RigidTransform(19).translation = ...
  [0 0 0];
smiData.RigidTransform(19).angle = 0;
smiData.RigidTransform(19).axis = [0 0 0];
smiData.RigidTransform(19).ID = 'B[3310:-:3547]';
smiData.RigidTransform(19).ID = convertCharsToStrings( ...
  smiData.RigidTransform(19).ID);
smiData.RigidTransform(20).translation = ...
  [7.1054273576010019E-15 -10.25 -2.1000000000000156];
smiData.RigidTransform(20).angle = 1.5707963267948966;
smiData.RigidTransform(20).axis = [-7.8504622934188758E-17 7.8504622934188758E-17 ...
                                   -1];
smiData.RigidTransform(20).ID = 'F[3310:-:3547]';
smiData.RigidTransform(20).ID = convertCharsToStrings( ...
  smiData.RigidTransform(20).ID);
smiData.RigidTransform(21).translation = ...
  [0 0 0];
smiData.RigidTransform(21).angle = 0;
smiData.RigidTransform(21).axis = [0 0 0];
smiData.RigidTransform(21).ID = 'B[3399:-:3454]';
smiData.RigidTransform(21).ID = convertCharsToStrings( ...
  smiData.RigidTransform(21).ID);
smiData.RigidTransform(22).translation = ...
  [0 1.1102230246251565E-16 -0.5];
smiData.RigidTransform(22).angle = 3.1415926535897931;
smiData.RigidTransform(22).axis = [0 2.2204460492503131E-16 -1];
smiData.RigidTransform(22).ID = 'F[3399:-:3454]';
smiData.RigidTransform(22).ID = convertCharsToStrings( ...
  smiData.RigidTransform(22).ID);
smiData.RigidTransform(23).translation = ...
  [0 0 0];
smiData.RigidTransform(23).angle = 0;
smiData.RigidTransform(23).axis = [0 0 0];
smiData.RigidTransform(23).ID = 'B[78:-:1863]';
smiData.RigidTransform(23).ID = convertCharsToStrings( ...
  smiData.RigidTransform(23).ID);
smiData.RigidTransform(24).translation = ...
  [0 0 -32];
smiData.RigidTransform(24).angle = 2.0943951023931953;
smiData.RigidTransform(24).axis = [0.57735026918962584 0.57735026918962584 ...
                                   0.57735026918962584];
smiData.RigidTransform(24).ID = 'F[78:-:1863]';
smiData.RigidTransform(24).ID = convertCharsToStrings( ...
  smiData.RigidTransform(24).ID);
smiData.RigidTransform(25).translation = ...
  [0 0 0];
smiData.RigidTransform(25).angle = 0;
smiData.RigidTransform(25).axis = [0 0 0];
smiData.RigidTransform(25).ID = 'B[78:-:2189]';
smiData.RigidTransform(25).ID = convertCharsToStrings( ...
  smiData.RigidTransform(25).ID);
smiData.RigidTransform(26).translation = ...
  [0 0 -8.6499999999999986];
smiData.RigidTransform(26).angle = 1.9504410117065309;
smiData.RigidTransform(26).axis = [0.67766147939433474 0.51998794185302111 ...
                                   0.51998794185302111];
smiData.RigidTransform(26).ID = 'F[78:-:2189]';
smiData.RigidTransform(26).ID = convertCharsToStrings( ...
  smiData.RigidTransform(26).ID);
smiData.RigidTransform(27).translation = ...
  [0 0 0];
smiData.RigidTransform(27).angle = 0;
smiData.RigidTransform(27).axis = [0 0 0];
smiData.RigidTransform(27).ID = 'B[78:-:427]';
smiData.RigidTransform(27).ID = convertCharsToStrings( ...
  smiData.RigidTransform(27).ID);
smiData.RigidTransform(28).translation = ...
  [0.5 -1.1102230246251565E-16 0];
smiData.RigidTransform(28).angle = 3.1415926535897931;
smiData.RigidTransform(28).axis = [-0.70710678118654746 0.70710678118654757 ...
                                   0];
smiData.RigidTransform(28).ID = 'F[78:-:427]';
smiData.RigidTransform(28).ID = convertCharsToStrings( ...
  smiData.RigidTransform(28).ID);
smiData.RigidTransform(29).translation = ...
  [0 -11.999999999999998 0];
smiData.RigidTransform(29).angle = 2.0943951023931953;
smiData.RigidTransform(29).axis = [-0.57735026918962584 -0.57735026918962584 ...
                                   -0.57735026918962584];
smiData.RigidTransform(29).ID = 'B[78:-:428]';
smiData.RigidTransform(29).ID = convertCharsToStrings( ...
  smiData.RigidTransform(29).ID);
smiData.RigidTransform(30).translation = ...
  [17 3.5527136788005009E-15 0];
smiData.RigidTransform(30).angle = 2.0943951023931953;
smiData.RigidTransform(30).axis = [0.57735026918962573 0.57735026918962584 ...
                                   0.57735026918962573];
smiData.RigidTransform(30).ID = 'F[78:-:428]';
smiData.RigidTransform(30).ID = convertCharsToStrings( ...
  smiData.RigidTransform(30).ID);
smiData.RigidTransform(31).translation = ...
  [0 0 0];
smiData.RigidTransform(31).angle = 0;
smiData.RigidTransform(31).axis = [0 0 0];
smiData.RigidTransform(31).ID = 'B[106:-:1110]';
smiData.RigidTransform(31).ID = convertCharsToStrings( ...
  smiData.RigidTransform(31).ID);
smiData.RigidTransform(32).translation = ...
  [-8.5 0 9.5];
smiData.RigidTransform(32).angle = 3.1415926535897931;
smiData.RigidTransform(32).axis = [1 0 0];
smiData.RigidTransform(32).ID = 'F[106:-:1110]';
smiData.RigidTransform(32).ID = convertCharsToStrings( ...
  smiData.RigidTransform(32).ID);
smiData.RigidTransform(33).translation = ...
  [21 0 9.5];
smiData.RigidTransform(33).angle = 2.0943951023931953;
smiData.RigidTransform(33).axis = [0.57735026918962584 0.57735026918962584 ...
                                   0.57735026918962584];
smiData.RigidTransform(33).ID = 'B[106:-:1631]';
smiData.RigidTransform(33).ID = convertCharsToStrings( ...
  smiData.RigidTransform(33).ID);
smiData.RigidTransform(34).translation = ...
  [16.999999999999986 0 1.0658141036401503E-14];
smiData.RigidTransform(34).angle = 2.0943951023931953;
smiData.RigidTransform(34).axis = [-0.57735026918962584 -0.57735026918962584 ...
                                   0.57735026918962584];
smiData.RigidTransform(34).ID = 'F[106:-:1631]';
smiData.RigidTransform(34).ID = convertCharsToStrings( ...
  smiData.RigidTransform(34).ID);
smiData.RigidTransform(35).translation = ...
  [0 0 0];
smiData.RigidTransform(35).angle = 0;
smiData.RigidTransform(35).axis = [0 0 0];
smiData.RigidTransform(35).ID = 'B[106:-:1865]';
smiData.RigidTransform(35).ID = convertCharsToStrings( ...
  smiData.RigidTransform(35).ID);
smiData.RigidTransform(36).translation = ...
  [1.2621774483536189E-29 0 -33.000000000000085];
smiData.RigidTransform(36).angle = 1.5707963267948968;
smiData.RigidTransform(36).axis = [1 -2.2759572004815705E-15 -2.2759572004815705E-15 ...
                                   ];
smiData.RigidTransform(36).ID = 'F[106:-:1865]';
smiData.RigidTransform(36).ID = convertCharsToStrings( ...
  smiData.RigidTransform(36).ID);
smiData.RigidTransform(37).translation = ...
  [0 0 0];
smiData.RigidTransform(37).angle = 0;
smiData.RigidTransform(37).axis = [0 0 0];
smiData.RigidTransform(37).ID = 'B[106:-:2970]';
smiData.RigidTransform(37).ID = convertCharsToStrings( ...
  smiData.RigidTransform(37).ID);
smiData.RigidTransform(38).translation = ...
  [-1.0097419586828951E-28 5.6843418860808015E-14 -32.499999999999986];
smiData.RigidTransform(38).angle = 1.5707963267948948;
smiData.RigidTransform(38).axis = [-1 -1.8041124150158794E-15 1.8041124150158794E-15 ...
                                   ];
smiData.RigidTransform(38).ID = 'F[106:-:2970]';
smiData.RigidTransform(38).ID = convertCharsToStrings( ...
  smiData.RigidTransform(38).ID);
smiData.RigidTransform(39).translation = ...
  [0 0 0];
smiData.RigidTransform(39).angle = 0;
smiData.RigidTransform(39).axis = [0 0 0];
smiData.RigidTransform(39).ID = 'B[106:-:3585]';
smiData.RigidTransform(39).ID = convertCharsToStrings( ...
  smiData.RigidTransform(39).ID);
smiData.RigidTransform(40).translation = ...
  [-9.5 0 23];
smiData.RigidTransform(40).angle = 3.1415926535897931;
smiData.RigidTransform(40).axis = [0.70710678118654746 0 0.70710678118654757 ...
                                   ];
smiData.RigidTransform(40).ID = 'F[106:-:3585]';
smiData.RigidTransform(40).ID = convertCharsToStrings( ...
  smiData.RigidTransform(40).ID);
smiData.RigidTransform(41).translation = ...
  [0 0 0];
smiData.RigidTransform(41).angle = 0;
smiData.RigidTransform(41).axis = [0 0 0];
smiData.RigidTransform(41).ID = 'B[428:-:106]';
smiData.RigidTransform(41).ID = convertCharsToStrings( ...
  smiData.RigidTransform(41).ID);
smiData.RigidTransform(42).translation = ...
  [0 -29 0];
smiData.RigidTransform(42).angle = 3.1415926535897931;
smiData.RigidTransform(42).axis = [-0.70710678118654746 -0.70710678118654757 ...
                                   0];
smiData.RigidTransform(42).ID = 'F[428:-:106]';
smiData.RigidTransform(42).ID = convertCharsToStrings( ...
  smiData.RigidTransform(42).ID);
smiData.RigidTransform(43).translation = ...
  [0 0 0];
smiData.RigidTransform(43).angle = 0;
smiData.RigidTransform(43).axis = [0 0 0];
smiData.RigidTransform(43).ID = 'B[1631:-:229]';
smiData.RigidTransform(43).ID = convertCharsToStrings( ...
  smiData.RigidTransform(43).ID);
smiData.RigidTransform(44).translation = ...
  [38 5.2735593669694946E-16 0];
smiData.RigidTransform(44).angle = 3.1415926535897931;
smiData.RigidTransform(44).axis = [0 0 -1];
smiData.RigidTransform(44).ID = 'F[1631:-:229]';
smiData.RigidTransform(44).ID = convertCharsToStrings( ...
  smiData.RigidTransform(44).ID);
smiData.RigidTransform(45).translation = ...
  [0 0 54];
smiData.RigidTransform(45).angle = 3.1415926535897931;
smiData.RigidTransform(45).axis = [1 0 0];
smiData.RigidTransform(45).ID = 'B[229:-:407]';
smiData.RigidTransform(45).ID = convertCharsToStrings( ...
  smiData.RigidTransform(45).ID);
smiData.RigidTransform(46).translation = ...
  [-3.2210481171079644E-14 3.6082248300317578E-16 -1.0000000000000284];
smiData.RigidTransform(46).angle = 3.1415926535897931;
smiData.RigidTransform(46).axis = [1 0 0];
smiData.RigidTransform(46).ID = 'F[229:-:407]';
smiData.RigidTransform(46).ID = convertCharsToStrings( ...
  smiData.RigidTransform(46).ID);
smiData.RigidTransform(47).translation = ...
  [0 0 0];
smiData.RigidTransform(47).angle = 0;
smiData.RigidTransform(47).axis = [0 0 0];
smiData.RigidTransform(47).ID = 'AssemblyGround[2189:61]';
smiData.RigidTransform(47).ID = convertCharsToStrings( ...
  smiData.RigidTransform(47).ID);
smiData.RigidTransform(48).translation = ...
  [0 0 1.5];
smiData.RigidTransform(48).angle = 3.1415926535897931;
smiData.RigidTransform(48).axis = [0.70710678118654746 0.70710678118654757 ...
                                   0];
smiData.RigidTransform(48).ID = 'AssemblyGround[2189:71]';
smiData.RigidTransform(48).ID = convertCharsToStrings( ...
  smiData.RigidTransform(48).ID);
smiData.RigidTransform(49).translation = ...
  [8.5 5.76120337263116E-16 0];
smiData.RigidTransform(49).angle = 3.1415926535897931;
smiData.RigidTransform(49).axis = [0 1 0];
smiData.RigidTransform(49).ID = 'AssemblyGround[2189:73]';
smiData.RigidTransform(49).ID = convertCharsToStrings( ...
  smiData.RigidTransform(49).ID);
smiData.RigidTransform(50).translation = ...
  [4.25 7.3612159321677284 0];
smiData.RigidTransform(50).angle = 3.1415926535897931;
smiData.RigidTransform(50).axis = [0 1 0];
smiData.RigidTransform(50).ID = 'AssemblyGround[2189:76]';
smiData.RigidTransform(50).ID = convertCharsToStrings( ...
  smiData.RigidTransform(50).ID);
smiData.RigidTransform(51).translation = ...
  [-4.2499999999999991 7.3612159321677311 0];
smiData.RigidTransform(51).angle = 3.1415926535897931;
smiData.RigidTransform(51).axis = [0 1 0];
smiData.RigidTransform(51).ID = 'AssemblyGround[2189:77]';
smiData.RigidTransform(51).ID = convertCharsToStrings( ...
  smiData.RigidTransform(51).ID);
smiData.RigidTransform(52).translation = ...
  [-8.5 1.6170701165383662E-15 0];
smiData.RigidTransform(52).angle = 3.1415926535897931;
smiData.RigidTransform(52).axis = [0 1 0];
smiData.RigidTransform(52).ID = 'AssemblyGround[2189:78]';
smiData.RigidTransform(52).ID = convertCharsToStrings( ...
  smiData.RigidTransform(52).ID);
smiData.RigidTransform(53).translation = ...
  [-4.25 -7.3612159321677266 0];
smiData.RigidTransform(53).angle = 3.1415926535897931;
smiData.RigidTransform(53).axis = [0 1 0];
smiData.RigidTransform(53).ID = 'AssemblyGround[2189:79]';
smiData.RigidTransform(53).ID = convertCharsToStrings( ...
  smiData.RigidTransform(53).ID);
smiData.RigidTransform(54).translation = ...
  [4.25 -7.3612159321677284 0];
smiData.RigidTransform(54).angle = 3.1415926535897931;
smiData.RigidTransform(54).axis = [0 1 0];
smiData.RigidTransform(54).ID = 'AssemblyGround[2189:80]';
smiData.RigidTransform(54).ID = convertCharsToStrings( ...
  smiData.RigidTransform(54).ID);
smiData.RigidTransform(55).translation = ...
  [0 0 -19.150000000000002];
smiData.RigidTransform(55).angle = 1.5707963267948968;
smiData.RigidTransform(55).axis = [-0 -1 -0];
smiData.RigidTransform(55).ID = 'AssemblyGround[2189:81]';
smiData.RigidTransform(55).ID = convertCharsToStrings( ...
  smiData.RigidTransform(55).ID);
smiData.RigidTransform(56).translation = ...
  [-2.6028224714424976E-15 0 -7.55];
smiData.RigidTransform(56).angle = 3.1415926535897931;
smiData.RigidTransform(56).axis = [-0.70710678118654746 0 0.70710678118654757 ...
                                   ];
smiData.RigidTransform(56).ID = 'AssemblyGround[2189:66]';
smiData.RigidTransform(56).ID = convertCharsToStrings( ...
  smiData.RigidTransform(56).ID);
smiData.RigidTransform(57).translation = ...
  [0 0 0];
smiData.RigidTransform(57).angle = 0;
smiData.RigidTransform(57).axis = [0 0 0];
smiData.RigidTransform(57).ID = 'RootGround[78]';
smiData.RigidTransform(57).ID = convertCharsToStrings( ...
  smiData.RigidTransform(57).ID);
smiData.Solid = struct;
smiData.Solid(1).mass = 0.039418917058256543;
smiData.Solid(1).CoM = [-5.435202240146479 -3.4507054201523948 -33.366182448218467 ...
                        ];
smiData.Solid(1).MoI = [22.374942641906117 18.765012621092612 11.90699022666924 ...
                        ];
smiData.Solid(1).PoI = [3.4032572002910442 -2.014176461316362 0.4656571706664534 ...
                        ];
smiData.Solid(1).color = [0.5 0.5 0.5];
smiData.Solid(1).opacity = 1;
smiData.Solid(1).ID = 'HESN0001_prt';
smiData.Solid(1).ID = convertCharsToStrings(smiData.Solid(1).ID);
smiData.Solid(2).mass = 0.011911533998965985;
smiData.Solid(2).CoM = [14.746354618273728 0 0];
smiData.Solid(2).MoI = [1.9568833232662146 0.98618315179506755 1.0102023730407264 ...
                        ];
smiData.Solid(2).PoI = [-0.01200986545344159 0 0];
smiData.Solid(2).color = [0.5 0.5 0.5];
smiData.Solid(2).opacity = 1;
smiData.Solid(2).ID = 'HFUC-8-100-2A-R_A_prt';
smiData.Solid(2).ID = convertCharsToStrings(smiData.Solid(2).ID);
smiData.Solid(3).mass = 0.0054781128285107594;
smiData.Solid(3).CoM = [-2.0928943917072687 -0.20282853911192697 -3.8293986500556763 ...
                        ];
smiData.Solid(3).MoI = [0.62496096609251661 1.5744246714336227 1.6828497944350187 ...
                        ];
smiData.Solid(3).PoI = [-0.0069779419451939219 -0.17009754139654848 0.031935634802011191 ...
                        ];
smiData.Solid(3).color = [0.5 0.5 0.5];
smiData.Solid(3).opacity = 1;
smiData.Solid(3).ID = 'HESN0006_prt';
smiData.Solid(3).ID = convertCharsToStrings(smiData.Solid(3).ID);
smiData.Solid(4).mass = 0.065302444014822866;
smiData.Solid(4).CoM = [0.0064484619814343617 -1.2251919425928208 -8.1090084715584823 ...
                        ];
smiData.Solid(4).MoI = [6.8289447587924013 5.6125536654077788 9.1735366349246323 ...
                        ];
smiData.Solid(4).PoI = [0.14434983018539183 0.0019637362449214804 0.0076034928006600607 ...
                        ];
smiData.Solid(4).color = [0.5 0.5 0.5];
smiData.Solid(4).opacity = 1;
smiData.Solid(4).ID = '3216W_BXTH_prt';
smiData.Solid(4).ID = convertCharsToStrings(smiData.Solid(4).ID);
smiData.Solid(5).mass = 0.00022601050313600526;
smiData.Solid(5).CoM = [0 0 -0.46629760540210252];
smiData.Solid(5).MoI = [0.00068285731630439276 0.00068285770076134287 0.0003035176199410687 ...
                        ];
smiData.Solid(5).PoI = [0 0 0];
smiData.Solid(5).color = [0.5 0.5 0.5];
smiData.Solid(5).opacity = 1;
smiData.Solid(5).ID = 'M2X04-6LOBE-ISO14583-A2-70_prt';
smiData.Solid(5).ID = convertCharsToStrings(smiData.Solid(5).ID);
smiData.Solid(6).mass = 0.0009609496888470894;
smiData.Solid(6).CoM = [11.251889293479028 -0.011283645085527153 -0.01128362311489234 ...
                        ];
smiData.Solid(6).MoI = [0.006251683698511471 0.032547200905493609 0.032547202221172744 ...
                        ];
smiData.Solid(6).PoI = [4.399283093664344E-7 -0.00010031820991431127 -0.00010031837247325718 ...
                        ];
smiData.Solid(6).color = [0.5 0.5 0.5];
smiData.Solid(6).opacity = 1;
smiData.Solid(6).ID = 'HESN0007_prt';
smiData.Solid(6).ID = convertCharsToStrings(smiData.Solid(6).ID);
smiData.Solid(7).mass = 0.011794768174602824;
smiData.Solid(7).CoM = [15.345858457483878 -0.0021400982233779585 0.0022439174923309367 ...
                        ];
smiData.Solid(7).MoI = [0.38995125690775534 0.27185324965205626 0.27185505477497179 ...
                        ];
smiData.Solid(7).PoI = [0 0.00014841736356518173 -0.00014796313466229643 ...
                        ];
smiData.Solid(7).color = [0.5 0.5 0.5];
smiData.Solid(7).opacity = 1;
smiData.Solid(7).ID = 'HFUC-8-100-2A-R_B_prt';
smiData.Solid(7).ID = convertCharsToStrings(smiData.Solid(7).ID);
smiData.Solid(8).mass = 0.00048868851515247757;
smiData.Solid(8).CoM = [0 0 -0.92359610490326083];
smiData.Solid(8).MoI = [0.0030170813719762103 0.0030170826667159133 0.00099270271287999487 ...
                        ];
smiData.Solid(8).PoI = [0 0 0];
smiData.Solid(8).color = [0.5 0.5 0.5];
smiData.Solid(8).opacity = 1;
smiData.Solid(8).ID = 'M2_5X06-6LOBE-ISO14583-A2-70_prt';
smiData.Solid(8).ID = convertCharsToStrings(smiData.Solid(8).ID);
smiData.Solid(9).mass = 0.0044676575895224706;
smiData.Solid(9).CoM = [6.7534659775897614 0 0];
smiData.Solid(9).MoI = [0.30124427891790229 0.289663161475328 0.29412518109934327 ...
                        ];
smiData.Solid(9).PoI = [0 0 0];
smiData.Solid(9).color = [0.5 0.5 0.5];
smiData.Solid(9).opacity = 1;
smiData.Solid(9).ID = 'HFUC-8-100-2A-R_C_prt';
smiData.Solid(9).ID = convertCharsToStrings(smiData.Solid(9).ID);
smiData.Solid(10).mass = 0.034141673787607969;
smiData.Solid(10).CoM = [-0.46973551907944433 0.3789373166075064 10.121431713072521 ...
                         ];
smiData.Solid(10).MoI = [19.697459332732667 12.452285158027031 28.022937392676283 ...
                         ];
smiData.Solid(10).PoI = [-0.05864606325671512 0.076612615494820513 0.0065660500243319457 ...
                         ];
smiData.Solid(10).color = [0.5 0.5 0.5];
smiData.Solid(10).opacity = 1;
smiData.Solid(10).ID = 'HESN0002_prt';
smiData.Solid(10).ID = convertCharsToStrings(smiData.Solid(10).ID);
smiData.Solid(11).mass = 0.003;
smiData.Solid(11).CoM = [0 0 2];
smiData.Solid(11).MoI = [0.07313135285979927 0.073131341651338055 0.13962845431205229 ...
                         ];
smiData.Solid(11).PoI = [0 0 0];
smiData.Solid(11).color = [0.5 0.5 0.5];
smiData.Solid(11).opacity = 1;
smiData.Solid(11).ID = '618-9_prt';
smiData.Solid(11).ID = convertCharsToStrings(smiData.Solid(11).ID);
smiData.Solid(12).mass = 0.01459281509517776;
smiData.Solid(12).CoM = [-19.970795715519351 0 -0.44354357943752];
smiData.Solid(12).MoI = [0.77590939351635946 4.6972459517992267 5.0464621419071456 ...
                         ];
smiData.Solid(12).PoI = [0 -0.823007355240669 0];
smiData.Solid(12).color = [0.5 0.5 0.5];
smiData.Solid(12).opacity = 1;
smiData.Solid(12).ID = 'HESN0005_prt';
smiData.Solid(12).ID = convertCharsToStrings(smiData.Solid(12).ID);
smiData.Solid(13).mass = 0.00027699665900131847;
smiData.Solid(13).CoM = [0 0 0];
smiData.Solid(13).MoI = [0.0028361579660207597 0.002836156533953325 0.0056261483901405319 ...
                         ];
smiData.Solid(13).PoI = [0 0 0];
smiData.Solid(13).color = [0.5 0.5 0.5];
smiData.Solid(13).opacity = 1;
smiData.Solid(13).ID = '4_3X12X1-ISO7093-A2_prt';
smiData.Solid(13).ID = convertCharsToStrings(smiData.Solid(13).ID);
smiData.Solid(14).mass = 0.0035892181289670444;
smiData.Solid(14).CoM = [0 0 1.9058084574533338];
smiData.Solid(14).MoI = [0.17458875420442746 0.174588795999193 0.33207362114734074 ...
                         ];
smiData.Solid(14).PoI = [0 0 0];
smiData.Solid(14).color = [0.5 0.5 0.5];
smiData.Solid(14).opacity = 1;
smiData.Solid(14).ID = 'HESN0008_prt';
smiData.Solid(14).ID = convertCharsToStrings(smiData.Solid(14).ID);
smiData.Solid(15).mass = 0.0013570469568223633;
smiData.Solid(15).CoM = [0 0 -0.45887951882521871];
smiData.Solid(15).MoI = [0.011532010236868274 0.011532018566789929 0.0061376015113421226 ...
                         ];
smiData.Solid(15).PoI = [0 0 0];
smiData.Solid(15).color = [0.5 0.5 0.5];
smiData.Solid(15).opacity = 1;
smiData.Solid(15).ID = 'M4X06-6LOBE-ISO14580-A2-70_prt';
smiData.Solid(15).ID = convertCharsToStrings(smiData.Solid(15).ID);
smiData.Solid(16).mass = 0.00018426774071019975;
smiData.Solid(16).CoM = [0 0 -2.44978175898868];
smiData.Solid(16).MoI = [0.000708239231333473 0.00070823932135842093 0.00016318777404422663 ...
                         ];
smiData.Solid(16).PoI = [0 0 0];
smiData.Solid(16).color = [0.5 0.5 0.5];
smiData.Solid(16).opacity = 1;
smiData.Solid(16).ID = 'M2X06-6LOBE-ISO14581-A2-70_prt';
smiData.Solid(16).ID = convertCharsToStrings(smiData.Solid(16).ID);
smiData.Solid(17).mass = 0.026642598569394053;
smiData.Solid(17).CoM = [-0.68799752664645775 0 27.913867214349338];
smiData.Solid(17).MoI = [8.41533674535616 28.233639292787338 20.919090317978924 ...
                         ];
smiData.Solid(17).PoI = [0 -0.17793695190932435 0];
smiData.Solid(17).color = [0.5 0.5 0.5];
smiData.Solid(17).opacity = 1;
smiData.Solid(17).ID = 'HESN0003_prt';
smiData.Solid(17).ID = convertCharsToStrings(smiData.Solid(17).ID);
smiData.Solid(18).mass = 0.00997979177638726;
smiData.Solid(18).CoM = [-0.56242260349555506 0 11.52291311657117];
smiData.Solid(18).MoI = [0.57502023499117016 0.54099302356828827 0.27131464812514405 ...
                         ];
smiData.Solid(18).PoI = [0 -0.001251225171357298 0];
smiData.Solid(18).color = [0.5 0.5 0.5];
smiData.Solid(18).opacity = 1;
smiData.Solid(18).ID = 'HESN0004_prt';
smiData.Solid(18).ID = convertCharsToStrings(smiData.Solid(18).ID);
smiData.RevoluteJoint = struct;
smiData.RevoluteJoint(1).Rz = struct;
smiData.RevoluteJoint(1).Rz.Pos = 89.999999999999986;
smiData.RevoluteJoint(1).ID = '[78:-:428]';
smiData.RevoluteJoint(1).ID = convertCharsToStrings( ...
  smiData.RevoluteJoint(1).ID);
smiData.RevoluteJoint(2).Rz = struct;
smiData.RevoluteJoint(2).Rz.Pos = 179.99999999999997;
smiData.RevoluteJoint(2).ID = '[106:-:1631]';
smiData.RevoluteJoint(2).ID = convertCharsToStrings( ...
  smiData.RevoluteJoint(2).ID);
smiData.RevoluteJoint(3).Rz = struct;
smiData.RevoluteJoint(3).Rz.Pos = 0;
smiData.RevoluteJoint(3).ID = '[229:-:407]';
smiData.RevoluteJoint(3).ID = convertCharsToStrings( ...
  smiData.RevoluteJoint(3).ID);

