function F = hd_axial_load(varargin)
% Copyright (C) 2024 Fondazione Istitito Italiano di Tecnologia (IIT)
% All Rights Reserved.

% Compute the axial load generated by the harmonic ddrive
% Ref: https://harmonicdrive.de/fileadmin/user_upload/2014_11-ED_1019657_HFUC-2A.pdf
% Page 38
%
% Inputs: the output torque [Nm] (default = 2.5 Nm)
% Outputs: the axial load [N]

%#ok<*NASGU>
T = 2.5;
if nargin > 0
    T = varargin{1};
end

% employ units
u = symunit;

% input data
hd_name = "HFUC-8-2A";
hd_size = 8;
T_out = T * u.N * u.m;  % output torque
mu = 0.07;              % friction coefficient
theta = 20 * u.deg;

D = hd_size * 2.54 * u.mm;            
F = 2 * (T_out / D) * mu * tan(unitConvert(theta, u.rad));
F = vpa(simplify(F), 5);
